### PR TITLE
Conventions PHP / spaces bracket

### PR DESCRIPTION
**Pull request by rvola**
Update spaces between bracket
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

### CODE REVIEW

**Comment by tillkruss** [comment]
I'm generating the `Additions.plist` file automatically, the next release will include your change. Thanks!

**Comment by rvola** [comment]
Sad for the first pull requests asked to have refused.
The next version comes with WordPress 4.6?
I will be interested to know your method to parse all functions, can you tell me more?

**Comment by tillkruss** [comment]
There you go ; )

**Comment by rvola** [comment]
I have not quite grasped what just happened.
What made you change your mind?

**Comment by tillkruss** [comment]
Now your first PR was merged.

The next version will come in a couple of days with 4.6. I'm using a simple PHP script to generate the file using the WP Seek API.

**Comment by rvola** [comment]
\O/ 
Thank you for the pro tips to wp seek.
I suggest you this library if you want to round out your plist files [https://github.com/rodneyrehm/CFPropertyList](https://github.com/rodneyrehm/CFPropertyList)

**Pull request merged**
